### ISSUE TITLE
Run code coverage tests in CI

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/glenside#115]

**Comment by gussmith23** [comment]
@ninehusky this might be a good next issue if you're interested in continuous integration! Let's talk about it in our meeting.

**Comment by ninehusky** [comment]
I've been doing some digging, and there are two code coverage options that I think could be worth exploring.

The first is [Tarpaulin](https://github.com/xd009642/tarpaulin), which is built on top of the Cargo build system. Because of this, I think it should integrate nicely with what we have - the big picture should ideally just be adding some extra steps onto running the tests with the usual flags. One thing that might make using this a bit tricky is the fact that the library only works with x86_64 processors running Linux, but I believe this might be okay with our current Docker settings.

The second option is [grcov](https://github.com/mozilla/grcov). This is a library built by Mozilla that generates HTML reports on code coverage, which could potentially be nicer if we want to build on code coverage CI later on (e.g., by emailing someone the report if code coverage dips). Another thing to be aware of is that grcov requires Nightly Rust, something that might mess things up.

I have a gut feeling that for what we want to do, Tarpaulin is probably the better choice. That being said, let me know what you think!

**Comment by gussmith23** [comment]
Let's move forward with Tarpaulin, then! It's def preferable that we stay on stable Rust. The limitation to x86 Linux systems should be fine, as that's exactly what our Github Actions instances run on.

**Comment by gussmith23** [comment]
The first step should be adding a new .yml file into the github actions folder to add a new action which runs Tarpaulin.
